### ISSUE TITLE
Work lists

### ISSUE THREAD

**Issue by ErikuNyang** [ECrecords/distance-vector-routing-protocols#1]
- [x] clean up the python-p2p-chat program.
  - remove unnecessary functions, 

- [x] Create Topology file for each server

- [x] we start our program, it reads a topology file

=> read topology file
=> server -t **topology-file-name** -i **time-interval-for-step**
=> initialize the routing table using topology file

- [ ] routing table will be updated using Bellman ford Algo

- [ ] message format (routing table) that need to be sent
=> python dictionary to handle message format, or any other idea?

- [ ] routing update
=> 1) update, 2) 

- [x] Display current routing table
=> display routing table
=> need to be sorted order from small ID to big.
=> ex) https://github.com/krishbhanushali/distance-vector

- [ ] Packet 
=> 

- [ ] step
=> routing table will be sent using Step command(when user asks)

- [x] update
=> update <server-ID1> <server-ID2> <Link Cost> 
=> update link cost only.
=> based on this, re-calculate routing table.

- [ ] Disable
=>  reuse / modify terminate fucntion
=>  you need to check if the given server is its neighbor. 

- [ ] Crash
=> reuse / modify exit function

**Comment by ErikuNyang** [comment]
server 2 Topology file
```
4
2
1 35.165.134.136 4901
2 13.57.50.95 4094
3 35.90.154.134 4096
4 18.217.37.142 7091
2 1 7
2 3 6
```

**Comment by haguar** [comment]
server 3 topology
`4
2
1 35.165.134.136 4901
2 13.57.50.95 4094
3 35.90.154.134 4096
4 18.217.37.142 7091
3 2 6
3 4 2`

**Comment by ErikuNyang** [comment]
![topology](https://user-images.githubusercontent.com/23006015/202337855-6ad4e86a-5b6a-436b-b8e6-1e0bc2e49c42.jpg)

**Comment by ECrecords** [comment]
4
2
1 35.165.134.136 4901
2 13.57.50.95 4094
3 35.90.154.134 4096
4 18.217.37.142 7091
1 4 5
1 3 4
1 2 7

**Comment by luhao1861** [comment]
server 4 topology
4
2
1 35.165.134.136 4901
2 13.57.50.95 4094
3 35.90.154.134 4096
4 18.217.37.142 7091
4 1 5
4 3 2
3 4 2
